# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import publisher_pb2 as publisher__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in publisher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class publicadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PedirDatos = channel.unary_unary(
                '/publisher.publicador/PedirDatos',
                request_serializer=publisher__pb2.reconocer_cliente.SerializeToString,
                response_deserializer=publisher__pb2.envio_datos.FromString,
                _registered_method=True)
        self.EnviarResultado = channel.unary_unary(
                '/publisher.publicador/EnviarResultado',
                request_serializer=publisher__pb2.resultado_cliente.SerializeToString,
                response_deserializer=publisher__pb2.resultados_server.FromString,
                _registered_method=True)


class publicadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PedirDatos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarResultado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_publicadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PedirDatos': grpc.unary_unary_rpc_method_handler(
                    servicer.PedirDatos,
                    request_deserializer=publisher__pb2.reconocer_cliente.FromString,
                    response_serializer=publisher__pb2.envio_datos.SerializeToString,
            ),
            'EnviarResultado': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarResultado,
                    request_deserializer=publisher__pb2.resultado_cliente.FromString,
                    response_serializer=publisher__pb2.resultados_server.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'publisher.publicador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('publisher.publicador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class publicador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PedirDatos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/publisher.publicador/PedirDatos',
            publisher__pb2.reconocer_cliente.SerializeToString,
            publisher__pb2.envio_datos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarResultado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/publisher.publicador/EnviarResultado',
            publisher__pb2.resultado_cliente.SerializeToString,
            publisher__pb2.resultados_server.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
