# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: publisher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'publisher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpublisher.proto\x12\tpublisher\"=\n\x11reconocer_cliente\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\relecion_envio\x18\x02 \x01(\x08\"K\n\x0b\x65nvio_datos\x12\x12\n\nrastreador\x18\x01 \x01(\t\x12\x0c\n\x04num1\x18\x02 \x01(\x05\x12\x0c\n\x04num2\x18\x03 \x01(\x05\x12\x0c\n\x04num3\x18\x04 \x01(\x05\"N\n\x11resultado_cliente\x12\x12\n\nid_cliente\x18\x01 \x01(\t\x12\x12\n\nrastreador\x18\x02 \x01(\t\x12\x11\n\tresultado\x18\x03 \x01(\x05\">\n\x11resultados_server\x12\x14\n\x0c\x66in_acciones\x18\x01 \x01(\x08\x12\x13\n\x0btotal_final\x18\x02 \x01(\x03\x32\xa3\x01\n\npublicador\x12\x44\n\nPedirDatos\x12\x1c.publisher.reconocer_cliente\x1a\x16.publisher.envio_datos\"\x00\x12O\n\x0f\x45nviarResultado\x12\x1c.publisher.resultado_cliente\x1a\x1c.publisher.resultados_server\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publisher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECONOCER_CLIENTE']._serialized_start=30
  _globals['_RECONOCER_CLIENTE']._serialized_end=91
  _globals['_ENVIO_DATOS']._serialized_start=93
  _globals['_ENVIO_DATOS']._serialized_end=168
  _globals['_RESULTADO_CLIENTE']._serialized_start=170
  _globals['_RESULTADO_CLIENTE']._serialized_end=248
  _globals['_RESULTADOS_SERVER']._serialized_start=250
  _globals['_RESULTADOS_SERVER']._serialized_end=312
  _globals['_PUBLICADOR']._serialized_start=315
  _globals['_PUBLICADOR']._serialized_end=478
# @@protoc_insertion_point(module_scope)
