# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: productor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'productor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproductor.proto\x12\x06worker\" \n\x0bTaskRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"A\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04num1\x18\x02 \x01(\x05\x12\x0c\n\x04num2\x18\x03 \x01(\x05\x12\x0c\n\x04num3\x18\x04 \x01(\x05\"@\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x05\"?\n\x0eSubmitResponse\x12\x13\n\x0bstop_signal\x18\x01 \x01(\x08\x12\x18\n\x10total_server_sum\x18\x02 \x01(\x03\x32{\n\x0fWorkCoordinator\x12,\n\x07GetTask\x12\x13.worker.TaskRequest\x1a\x0c.worker.Task\x12:\n\x0cSubmitResult\x12\x12.worker.TaskResult\x1a\x16.worker.SubmitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=27
  _globals['_TASKREQUEST']._serialized_end=59
  _globals['_TASK']._serialized_start=61
  _globals['_TASK']._serialized_end=126
  _globals['_TASKRESULT']._serialized_start=128
  _globals['_TASKRESULT']._serialized_end=192
  _globals['_SUBMITRESPONSE']._serialized_start=194
  _globals['_SUBMITRESPONSE']._serialized_end=257
  _globals['_WORKCOORDINATOR']._serialized_start=259
  _globals['_WORKCOORDINATOR']._serialized_end=382
# @@protoc_insertion_point(module_scope)
